# Generated by Django 4.2.24 on 2025-09-26 06:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contato', '0002_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reserva',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
